version: "3"
services:
    web:
        # replace username/repo:tag with your name and image details
        image: paca ## e.g. image: cajahyba/auladocker:aula2 
        deploy:
          replicas: 5
          restart_policy:
            condition: on-failure
        ports:
          - "8080:80"
        environment:
          - "ASPNETCORE_URLS=http://0.0.0.0"
          - "ASPNETCORE_ENVIRONMENT=Development"
        networks:
          - webnet

    mysql-master:
        image: 'bitnami/mysql:latest'
        ports:
          - "7701:3306"
        environment:
          - MYSQL_REPLICATION_MODE=master
          - MYSQL_REPLICATION_USER=repl_user
          - MYSQL_REPLICATION_PASSWORD=repl_password
          - MYSQL_ROOT_PASSWORD=master_root_password
          - MYSQL_USER=example_user
          - MYSQL_PASSWORD=mysqlpwd
          - MYSQL_DATABASE=example
         
        networks:
            webnet:
                ipv4_address: 10.0.0.3
                aliases:
                - "pgcluster"            
          
    mysql-slave:
        image: 'bitnami/mysql:latest'
        ports:
          - "7702:3306"
        depends_on:
          - mysql-master
        environment:
          - MYSQL_REPLICATION_MODE=slave
          - MYSQL_REPLICATION_USER=repl_user
          - MYSQL_REPLICATION_PASSWORD=repl_password
          - MYSQL_MASTER_HOST=mysql-master
          - MYSQL_MASTER_PORT_NUMBER=3306
          - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
        
        networks:
            webnet:
             ipv4_address: 10.0.0.4
             aliases:
               - "pgcluster"                 
                
networks:        
   webnet:
    ipam:
      driver: default
      config:
        - subnet: "10.0.0.0/24"

   

   
    

  
  
  
