version: "3"
services:
  web:
    image: paca
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
    ports:
      - "8080:80"
    environment:
      - "ASPNETCORE_URLS=http://0.0.0.0"
      - "ASPNETCORE_ENVIRONMENT=Development"
    networks:
      - net
  mysql-master:
    image: bitnami/mysql:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "7701:3306"
    networks:
      - net
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=master_root_password
      - MYSQL_USER=example_user
      - MYSQL_PASSWORD=mysqlpwd
      - MYSQL_DATABASE=example
  mysql-slave:
    image: bitnami/mysql:latest
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "7702:3306"
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=master_root_password
    networks:
      net:
        aliases:
          - "pgcluster"
networks:
  net:
