version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: leosena21/cajahyba:latest ## e.g. image: cajahyba/auladocker:aula2 
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "4000:80"
    networks:
      - webnet
networks:
  webnet:
  
  
  
   0.0.0.0:32774->80/tcp